name: Docker Image CI

on:
  push:
    branches:
      - main
      - staging
      - prod

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run unit test
      run: pytest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devops:latest
