name: Docker Image CI

on:
  push:
    branches:
      - main
      - staging
      - prod

jobs:

  staging:
    if: github.ref == 'refs/heads/main' && github.ref == 'refs/heads/staging'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run unit test
      run: pytest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag daoducanhc/devops:staging
        docker push daoducanhc/devops:staging


#  prod:
#     if: github.ref == 'refs/heads/main' && github.ref == 'refs/heads/prod'
    
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
      
#     - name: Install dependencies
#       run: pip install -r requirements.txt
      
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag daoducanhc/devops:prod
